# Info about you
name: Takuya Matsuyama
position: Job Title
email: u722117c@ecs.osaka-u.ac.jp
company_name: Osaka University
company_url: https://www.yourcompany.com
place_name: Osaka, Japan

# Blog info
title: Personal Website
description: Blog
url: https://suyamat.github.io
main_github_io: false
long_description: >-
    Hi! I'm Takuya Matsuyama.

# Social links
github_url: https://github.com/suyamat
# linkedin_url: http://www.linkedin.com/in/your-name
social:
  links:
    # - http://www.linkedin.com/in/your-name
    - https://github.com/suyamat

# Images + files
logo: assets/img/headshot.svg
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
