# Info about you
name: 松山 卓矢
position: 修士課程一年生
email: 
company_name: 大阪大学
company_url: https://www.fbs.osaka-u.ac.jp/ja
place_name: 大阪

# Blog info
title: 松山 卓矢
description: Personal Website
url: https://suyamat.github.io/ja
main_github_io: false
long_description: >-
    初めまして! 大阪大学の知覚認知神経科学研究室（<a href="https://nishimotolab.org/">西本研究室</a>）に所属しています、修士課程一年生の松山卓矢です。
    AIと脳の融合を目指したテーマに興味があり、画像・動画・音楽・言語処理などのAIを用いて脳機能の解明に取り組んでいます。

# Social links
github_url: https://github.com/suyamat
# linkedin_url: http://www.linkedin.com/in/your-name
social:
  links:
    # - http://www.linkedin.com/in/your-name
    - https://github.com/suyamat

# Images + files
logo: assets/img/headshot.svg
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: light  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - white mode
colors:
  text: 333
  tag: dbefdc
  tag_hover: 93cf95
  header_background: ffffff
  header_text: 00000
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
